spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    schema-username: app
  jpa:
    hibernate:
      ddl-auto: validate
    generate-ddl: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true

multitenant:
  system:
    schema: app
    location: db/migration/default
  tenant:
    location: db/migration/tenant
